# macOS specific dependencies

FIND_LIBRARY(APP_KIT_LIBRARY AppKit)
FIND_LIBRARY(APP_SERVICES_LIBRARY ApplicationServices)
FIND_LIBRARY(AV_FOUNDATION_LIBRARY AVFoundation)
FIND_LIBRARY(CORE_MEDIA_LIBRARY CoreMedia)
FIND_LIBRARY(CORE_VIDEO_LIBRARY CoreVideo)
FIND_LIBRARY(FOUNDATION_LIBRARY Foundation)
FIND_LIBRARY(VIDEO_TOOLBOX_LIBRARY VideoToolbox)
FIND_LIBRARY(METAL_LIBRARY Metal)
FIND_LIBRARY(METAL_KIT_LIBRARY MetalKit)
FIND_LIBRARY(IO_SURFACE_LIBRARY IOSurface)
FIND_LIBRARY(CORE_GRAPHICS_LIBRARY CoreGraphics)
FIND_LIBRARY(SCREEN_CAPTURE_KIT_LIBRARY ScreenCaptureKit)

if(SUNSHINE_ENABLE_TRAY)
    FIND_LIBRARY(COCOA Cocoa REQUIRED)
endif()

set(MACOS_REQUIRED_FRAMEWORKS
    ${APP_KIT_LIBRARY}
    ${APP_SERVICES_LIBRARY}
    ${AV_FOUNDATION_LIBRARY}
    ${CORE_MEDIA_LIBRARY}
    ${CORE_VIDEO_LIBRARY}
    ${FOUNDATION_LIBRARY}
    ${VIDEO_TOOLBOX_LIBRARY}
    ${METAL_LIBRARY}
    ${IO_SURFACE_LIBRARY}
    ${CORE_GRAPHICS_LIBRARY}
)

if(SCREEN_CAPTURE_KIT_LIBRARY)
    list(APPEND MACOS_REQUIRED_FRAMEWORKS ${SCREEN_CAPTURE_KIT_LIBRARY})
    add_compile_definitions(SUNSHINE_MACOS_SCREENCAPTUREKIT=1)
    message(STATUS "ScreenCaptureKit found - enabling modern screen capture")
else()
    message(STATUS "ScreenCaptureKit not found - using legacy AVCaptureScreenInput")
endif()
